### ISSUE TITLE
Minor App Tweaks (7/7 Complete)

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#103]
Update disclaimer (different for freeMapView vs pathMapView) (Complete)
Add walking guy to custom widget next to distance/time (Complete)
Update delete confirmation size (Complete)
Finalize all widget colors/hover colors/loading colors/background colors  (Complete)
Update all logos with new logo (Complete)
Make button that changes route view pretty (Complete)
Add animations (Complete)

**Comment by rjgolden** [comment]
- Add app theme font to custom widget
- Update disclaimer (different for freeMapView vs pathMapView)
- Add walking guy to custom widget next to distance/time
- Update delete confirmation size
- Finalize all widget colors/hover colors/loading colors/background colors
- Update all logos with new logo
