### ISSUE TITLE
US2: User login

### ISSUE THREAD

**Issue by rbutera03** [rbutera03/WalkPointURI#20]
US2: User login
AS A returning user, I WANT TO log into my account SO THAT I can access my personalized walking routes and other app features.
SCENARIO:
GIVEN the user is on the login page,
WHEN they enter valid credentials and submit,
THEN they are logged into the app WITHIN a few seconds,
AND redirected to the dashboard page WITHIN 2 seconds

GIVEN the user is on the login page,
WHEN they enter an email that exists in the system but the password is incorrect,
THEN the system displays an error message (e.g., "Incorrect password. Please try again or reset your password.").

GIVEN the user is on the login page,
WHEN they enter an email address that is not associated with any account,
THEN the system displays an error message (e.g., "No account found with this email. Please sign up or try again.").

GIVEN the user is on the login page,
WHEN they enter an email address in an invalid format (e.g., "userexample.com" or "user@.com"),
THEN the system displays an error message (e.g., "Please enter a valid email address.").

GIVEN the user is on the login page,
WHEN they leave the email or password field blank and try to log in,
THEN the system displays an error message (e.g., "Both email and password are required. Please fill in all fields.").

**Comment by keremerkmen** [comment]
US2: User login
AS A returning user, I WANT TO log into my account SO THAT I can access my personalized walking routes and other app features.
SCENARIO:
GIVEN the user is on the login page,
WHEN they enter valid credentials and submit,
THEN they are logged into the app WITHIN a few seconds,
AND redirected to the dashboard page WITHIN 2 seconds.
